# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout
      - run: 
          command: |    
            set +e   
            sudo apt-get update && sudo apt-get upgrade
            openssl version -a
            sudo apt install build-essential checkinstall zlib1g-dev -y

            cd /usr/local/src/
            sudo wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz
            sudo tar -xf openssl-1.1.1c.tar.gz
            cd openssl-1.1.1c

            ls #for testing windows installation
        


            echo "BEFORE PYTHON"
            sudo apt-get install python3
            sudo apt-get install python3-pip
            pip3 install mkdocs-material
            cd www
            mkdocs gh-deploy --force



workflows:
  version: 2

  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/

                      
          
      

