# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout
      - run: 
          command: |    
            set +e   
            sudo apt-get install python3
            sudo apt-get install python3-pip
            pip install --upgrade pip
            pip install mkdocs-material
workflows:
  version: 2

  build_and_test:
    jobs:
      - build
     

