# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout
      - run: 
          command: |    
            set +e   
            sudo apt-get install python3
            sudo apt-get install python3-pip
            pip3 install mkdocs-material
            cd www
            mkdocs gh-deploy --force
            echo "testing"
            echo "Installing tfswitch locally"
            wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh 
            chmod 755 install.sh
            ./install.sh -b bin-directory

            CUSTOMBIN=`pwd`

            mkdir $CUSTOMBIN

            ./bin-directory/tfswitch 0.11.7 --bin $CUSTOMBIN

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
     

