site_name: sandbox
site_description: Testing sandbox
copyright: This project is maintained by warrensbox
repo_name: warrensbox/terraform-switcher
repo_url: https://github.com/warrensbox/terraform-switcher
site_url: https://sandbox.warrensbox.com

theme:
    name: material
    palette:
        primary: indigo
    favicon: static/favicon_tfswitch_16.png
    logo: static/logo.png

nav:
    - index.md
    - Install.md
    - Quick-Start.md
    - Continuous-Integration.md
    - Upgrade-or-Uninstall.md
    - How-to-Contribute.md
    - Troubleshoot.md
    

