site_name: sandbox
site_description: Testing sandbox
copyright: Made with ❤️ by Warrensbox contributors.
repo_name: warrensbox/terraform-switcher
repo_url: https://github.com/warrensbox/terraform-switcher
edit_uri: edit/master/www/docs/

theme:
    name: material

nav:
    - index.md
    - intro.md

